server:
  port: 32003
spring:
  application:
    name: 'valera-zuul-server'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:32001/eureka}
  instance:
    preferIpAddress: true
zuul:
  routes:
    main-service-route:
      path: /
      serviceId: main-service
    main-service-styles:
      path: /*.css
      serviceId: main-service
    main-service-scripts:
      path: /*.js
      serviceId: main-service
    main-service-assets:
      path: /assets/images/coder.png
      serviceId: main-service
    main-service-api:
      path: /api/**
      serviceId: main-service
      stripPrefix: false
    second-service-api:
      path: /second-service/**
      url: http://localhost:32181
      stripPrefix: false
    test-service-route:
      path: /test-service/**
      serviceId: test-service
  ignored-services: '*'
ribbon:
  ReadTimeout: 60000

