spring:
  application:
    name: valera-config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/conf
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:32001/eureka}
server:
  port: 32002
test-var: asdasdasd